{% set name = "clingo-lpx" %}
{% set version = "1.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/potassco/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3f62d2818b8bade4883c52a84337d75359a1b32e732a00e09f947846ac7bfee9
  patches:
    - find-python.patch

build:
  number: 0

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - make  # [unix]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - clingo >=5.5.1
    - gmp  # [unix]
  run:
    - python
    # clingo breaks the API with minor version increments
    - {{ pin_compatible('clingo', min_pin='x.x', max_pin='x.x') }}
    - cffi  # [python_impl == 'cpython']
    - gmp  # [unix]

test:
  commands:
    - clingo-lpx --version
    - python -m clingolpx --version
    - pip check
  requires:
    - pip

about:
  home: https://potassco.org/
  license: MIT
  summary: A solver for logic programs with linear constraints.
  description: The clingo-lpx solver extends the clingo ASP system with support for linear constraints over rational numbers.
  license_file: LICENSE
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}

extra:
  recipe-maintainers:
    - rkaminsk
